### ISSUE TITLE
FramesManager addPageCallback doesn't handle undefined frame

### ISSUE THREAD

**Issue by soundofspace** [ulixee/unblocked#86]
FramesManager addPageCallback doesn't handle an undefined frame returned by getFrameForExecutionContext.

Not entirely sure if it should ever get here if frame is undefined or it is the symptom of a larger problem. Current problem right now is that addPageCallback will call the onCallback function with frame undefined resulting in :
```
UnhandledRejection; TypeError: Cannot read properties of undefined (reading 'frameId')
agent/main/lib/InjectedScripts.ts:46:48
```

What worries me a bit more, but might just be my personal ide setup is that TS thinks is can't be undefined, hence not giving compile time errors (which is probably how this got under the radar).
<img width="599" alt="image" src="https://github.com/ulixee/unblocked/assets/116737867/d2703d4b-8359-4326-89d2-126b78f25971">

<img width="912" alt="image" src="https://github.com/ulixee/unblocked/assets/116737867/a790e664-0499-4d6f-915d-36f079227022">

But looking at the function is can definitely return undefined
<img width="666" alt="image" src="https://github.com/ulixee/unblocked/assets/116737867/3e8c0453-2ca7-4139-9073-9a29830d3250">

**Comment by blakebyrnes** [comment]
I'm thinking we should probably just not call the callback if there's no frame. It seems like it's just too confusing to try to handle a if a frame is already detached. 

``` const frame = this.getFrameForExecutionContext(event.executionContextId);
        if (frame) onCallback(event.payload, frame);
```
